import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import ToastNotification from "@/components/ui/ToastNotification";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "POS - Frontexn ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-gray-200 min-h-screen`}>
        <ToastNotification />
        {children}
      </body>
    </html>
  );
}
